brasileirão = ('Atlético-mg', 'Flamengo', 'Palmeiras', 'Fortaleza', 'Corinthians', 'Bragantino', 'Fluminense', 'America-mg', 'Atlético-go', 'Santos', 'Ceará', 'Internacional', 'São Paulo', 'Athletico-pr', 'Cuiabá', 'Juventude', 'Grêmio', 'Bahia', 'Sport', 'Chapecoense')
print('-=-' * 30)
print(f'Lista de times do Brasileirão: {brasileirão}')
print('-=-' * 30)
print(f'Os 5 primeiros são: {brasileirão[0:5]}')
print('-=-' * 30)
print(f'Os 4 últimos são: {brasileirão[-4:]}')
print('-=-' * 30)
print(f'Times em ordem alfabética: {sorted(brasileirão)}')
print('-=-' * 30)
index = brasileirão.index('Chapecoense')
print(f'O Chapecoense está na {index + 1}ª posição.') 